[package]
name = "nosql"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
futures = "0.3.34"
rand = "0.10.2"
serde = { version = "1.0.229", features=["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
uuid = { version = "1.26.0", features = ["v4"] }