name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # ----------------------------------------------------
      # For RUST Projects:
      # ----------------------------------------------------
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run Cargo Tests
        run: cargo test --all-targets --verbose